server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhengweicheng
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    timeout: 1000 #超时时间
    jedis:
      pool:
        min-idle: 5 #最小空闲
        max-idle: 10 #最大空闲
        max-wait: -1 #最大等待时间、无限等待

  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


rocketmq:
  #当用到rocketMQ时必须配置的两项
  name-server: localhost:9876
  producer:
    group: file_group

mybatis:
  type-aliases-package: zwc.pojo
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    name: log/log.log
  level:
    root: info
    wuhobin: debug

#模板文件上传路径
upload_dir: upload/

#校验文件存储路径
check_dir: check/

#校验结果下载路径
download_dir: download/